In [ ]:
#комментарий - Мне очень трудно называть функции и переменные адекватно их смыслу, т.к. не владею англ) . 
#Постараюсь все же придерживаться в наименованиях смысла хотя бы транслитерируя их)

In [ ]:
#задача1

In [16]:
import numpy as np

n=10
def n_a_fun(n):
    return np.arange(n-1,-1,-1)

In [17]:
n_a_fun(n)


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
#задача2

In [25]:
n_a2=np.diag(np.arange(n-1,-1,-1),0)
n_a2

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [27]:
sum(sum(n_a2))

45

In [28]:
#задача3


In [30]:
a=np.array([[4,2,1],[1,3,0],[0,5,4]])

In [31]:
b=np.array([4,12,-3])

In [32]:
from numpy import linalg

In [33]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [ ]:
#доп------------------------------------------

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [75]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [76]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [77]:
import matplotlib.pyplot as plt

In [78]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [79]:
ind_=0
num_=0
min_delta=1000
for i in users_stats:

    if min_delta>np.arccos( cosine( next_user_stats, i ) ):
        
        min_delta=np.arccos( cosine( next_user_stats, i ) )
        num_=ind_
    ind_+=1
    

In [81]:
print('Максимальная схожесть у пользователя с  номером',num_)

Максимальная схожесть у пользователя с  номером 7
